"use client";

import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Bot, User, Download } from "lucide-react";
import type { Message } from "@/lib/types";
import { cn } from "@/lib/utils";
import { MarkdownRenderer } from "./markdown-renderer";
import { useTypewriter } from "@/hooks/use-typewriter";
import Image from "next/image";
import { Button } from "../ui/button";

interface ChatMessageProps {
  message: Message;
}

export function ChatMessage({ message }: ChatMessageProps) {
  const isModel = message.role === "model";
  const displayedContent = useTypewriter(message.content, isModel && !!message.isStreaming);

  return (
    <div className={cn("flex items-start gap-4", isModel ? "" : "justify-end")}>
      <div className={cn("flex items-start gap-4", isModel ? "" : "flex-row-reverse")}>
        <Avatar className={cn("h-8 w-8", isModel ? "" : "bg-primary text-primary-foreground")}>
          {isModel ? (
            <AvatarFallback className="bg-accent text-accent-foreground">
              <Bot className="h-5 w-5" />
            </AvatarFallback>
          ) : (
            <AvatarFallback>
              <User className="h-5 w-5" />
            </AvatarFallback>
          )}
        </Avatar>
        <div
          className={cn(
            "max-w-[85%] rounded-lg p-4 shadow-sm",
            isModel ? "rounded-tl-none bg-card" : "rounded-tr-none bg-primary text-primary-foreground"
          )}
        >
          {message.type === 'image' ? (
            <div className="space-y-3">
              <Image
                src={message.content}
                alt="Generated by OngwaeGPT"
                width={512}
                height={512}
                className="rounded-md"
                data-ai-hint="ai generated"
              />
              <Button variant="ghost" size="sm" asChild className="w-full">
                <a href={message.content} download={`ongwaegpt-image-${message.id}.png`}>
                  <Download className="mr-2 h-4 w-4" />
                  Download Image
                </a>
              </Button>
            </div>
          ) : (
            <MarkdownRenderer content={displayedContent} />
          )}
        </div>
      </div>
    </div>
  );
}
