"use client";

import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Bot, User } from "lucide-react";
import type { Message } from "@/lib/types";
import { cn } from "@/lib/utils";
import { MarkdownRenderer } from "./markdown-renderer";
import { Logo } from "./logo";
import { useTypewriter } from "@/hooks/use-typewriter";
import Image from "next/image";

interface ChatMessageProps {
  message: Message;
}

export function ChatMessage({ message }: ChatMessageProps) {
  const isAssistant = message.role === "assistant";
  const displayedContent = useTypewriter(message.content, isAssistant && !!message.isStreaming);

  return (
    <div className={cn("flex items-start gap-4", isAssistant ? "" : "flex-row-reverse")}>
      <Avatar className={cn("h-8 w-8", isAssistant ? "" : "bg-primary text-primary-foreground")}>
        {isAssistant ? (
          <>
            <div className="flex h-full w-full items-center justify-center rounded-full bg-accent">
              <Logo className="h-5 w-5 text-accent-foreground" />
            </div>
          </>
        ) : (
          <AvatarFallback>
            <User className="h-5 w-5" />
          </AvatarFallback>
        )}
      </Avatar>
      <div
        className={cn(
          "max-w-[85%] rounded-lg p-4 shadow-sm",
          isAssistant ? "rounded-tl-none bg-card" : "rounded-tr-none bg-primary text-primary-foreground"
        )}
      >
        {message.type === 'image' ? (
          <Image
            src={message.content}
            alt="Generated by OngwaeGPT"
            width={512}
            height={512}
            className="rounded-md"
            data-ai-hint="ai generated"
          />
        ) : (
          <MarkdownRenderer content={isAssistant && message.isStreaming ? displayedContent : message.content} />
        )}
      </div>
    </div>
  );
}
